### ISSUE TITLE
Select2 for Multi Select with Tailwind CSS

### ISSUE THREAD

**Issue by mayanxoni** [Xibel/select2-tailwindcss#1]
Hi @Xibel, thanks for the awesome component. I came across your repo from [Select2 forums](https://forums.select2.org/t/tailwind-css-style/1339/10) and [Laracasts Discussion](https://laracasts.com/discuss/channels/javascript/change-styling-to-tailwind-for-javascript-packages) and wondered if you have also created a module for selecting multiple select options using Tailwind CSS.

**Comment by Xibel** [comment]
Hi @mayanxoni, no I have not added the support for the multiple select option. I did not need that. Maybe in the future.

**Comment by mayanxoni** [comment]
No problem @Xibel, thanks for sharing!
