### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by johntom** [Xibel/select2-tailwindcss#3]
Hi 
Very interested in repo and trying to install. So I  installed live-server extentsion but get the following. I also don't see select2 in packages.
TIA

```
live-server : The term 'live-server' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify 
that the path is correct and try again.
At line:1 char:1
+ live-server
+ ~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (live-server:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
win10
node 14.17.0
npm 6.14.3

**Comment by Xibel** [comment]
Select2 is not being installed in packages. It is being called from a CDN in the index.html. The only package that is being installed is tailwindcss, autoprefixer and postcss-cli.
I am using:
MacOS
Node v16
npm 7.11.2

I see others using the repo without problems so I assume this is a local issue with your environment. However, I updated the package dependencies. Please retry with the above versions.
