### ISSUE TITLE
Weird initial state

### ISSUE THREAD

**Issue by jonathanoeijoeng** [Xibel/select2-tailwindcss#8]
Hi. Thanks so much for working on this. It help me a lot.
I have put your script in app.css but do you know why it's initial place like screenshot attached? It should only has 1 row, right? Btw, I use select2 multiple.
<img width="890" alt="image" src="https://user-images.githubusercontent.com/7046560/185550648-ddddd8f9-0a3b-4bbe-bb65-71b13fa4ed00.png">

**Comment by Xibel** [comment]
Hi Jonathan, I do not know what is happening. You are using multiple so there will be more than 1 row. That is normal. But why it shows you that border. I think it has something to do with your initial style of your app.css. Your drop down is also not as it should be. You see some rounded div behind it. You know what I mean?

Can you please try the original example alone to if this happens on your local environment?
